package com.bookingeventflow.event.service;

import com.bookingeventflow.event.domain.model.EventStatus;
import com.bookingeventflow.event.entity.EventEntity;
import com.bookingeventflow.event.exception.EventNotFoundException;
import com.bookingeventflow.event.presentation.request.CreateEventRequest;
import com.bookingeventflow.event.presentation.request.UpdateEventRequest;
import com.bookingeventflow.event.presentation.response.EventResponse;
import com.bookingeventflow.event.repository.EventRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.OptimisticLockingFailureException;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.transaction.support.TransactionTemplate;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@ActiveProfiles("test")
@Testcontainers
class EventServiceIntegrationTest {

    @Container
    static final PostgreSQLContainer<?> POSTGRES =
            new PostgreSQLContainer<>("postgres:17")
                    .withDatabaseName("event_service")
                    .withUsername("event_service")
                    .withPassword("event_service");

    @DynamicPropertySource
    static void configureDatabase(
            DynamicPropertyRegistry registry
    ) {

        registry.add(
                "spring.datasource.url",
                POSTGRES::getJdbcUrl
        );

        registry.add(
                "spring.datasource.username",
                POSTGRES::getUsername
        );

        registry.add(
                "spring.datasource.password",
                POSTGRES::getPassword
        );

        registry.add(
                "spring.datasource.driver-class-name",
                POSTGRES::getDriverClassName
        );

        registry.add(
                "spring.flyway.url",
                POSTGRES::getJdbcUrl
        );

        registry.add(
                "spring.flyway.user",
                POSTGRES::getUsername
        );

        registry.add(
                "spring.flyway.password",
                POSTGRES::getPassword
        );

        registry.add(
                "spring.jpa.show-sql",
                () -> "false"
        );

        registry.add(
                "spring.jpa.properties.hibernate.format_sql",
                () -> "true"
        );
    }

    @Autowired
    private EventService eventService;

    @Autowired
    private EventRepository eventRepository;

    @Autowired
    private TransactionTemplate transactionTemplate;

    @BeforeEach
    void setUp() {

        eventRepository.deleteAll();
        eventRepository.flush();
    }

    // =====================================================================
    // CREATE
    // =====================================================================

    @Test
    void create_shouldPersistEvent() {

        CreateEventRequest request =
                new CreateEventRequest(
                        "Rock Concert",
                        "Live concert",
                        Instant.parse(
                                "2026-12-20T19:00:00Z"
                        )
                );

        EventResponse result =
                eventService.create(request);

        /*
         * UUID is generated by Hibernate/database.
         */
        assertNotNull(result.id());

        assertEquals(
                0L,
                result.version()
        );

        assertEquals(
                "Rock Concert",
                result.name()
        );

        assertEquals(
                "Live concert",
                result.description()
        );

        assertEquals(
                EventStatus.DRAFT,
                result.status()
        );

        EventEntity persisted =
                eventRepository.findById(result.id())
                        .orElseThrow();

        assertEquals(
                result.id(),
                persisted.id()
        );

        assertEquals(
                0L,
                persisted.version()
        );

        assertEquals(
                "Rock Concert",
                persisted.getName()
        );

        assertEquals(
                "Live concert",
                persisted.getDescription()
        );

        assertEquals(
                EventStatus.DRAFT,
                persisted.getStatus()
        );
    }

    // =====================================================================
    // GET BY ID
    // =====================================================================

    @Test
    void getById_shouldReturnPersistedEvent() {

        EventResponse created =
                eventService.create(
                        new CreateEventRequest(
                                "Rock Concert",
                                "Live concert",
                                Instant.parse(
                                        "2026-12-20T19:00:00Z"
                                )
                        )
                );

        assertNotNull(created.id());

        EventResponse result =
                eventService.getById(created.id());

        assertEquals(
                created.id(),
                result.id()
        );

        assertEquals(
                0L,
                result.version()
        );

        assertEquals(
                "Rock Concert",
                result.name()
        );

        assertEquals(
                "Live concert",
                result.description()
        );

        assertEquals(
                EventStatus.DRAFT,
                result.status()
        );
    }

    @Test
    void getById_shouldThrowEventNotFoundException_whenMissing() {

        UUID id = UUID.randomUUID();

        assertThrows(
                EventNotFoundException.class,
                () -> eventService.getById(id)
        );
    }

    // =====================================================================
    // GET ALL
    // =====================================================================

    @Test
    void getAll_shouldReturnPersistedEvents() {

        eventService.create(
                new CreateEventRequest(
                        "Rock Concert",
                        "Live concert",
                        Instant.parse(
                                "2026-12-20T19:00:00Z"
                        )
                )
        );

        eventService.create(
                new CreateEventRequest(
                        "Jazz Festival",
                        "Live jazz",
                        Instant.parse(
                                "2026-12-21T19:00:00Z"
                        )
                )
        );

        List<EventResponse> events =
                eventService.getAll();

        assertEquals(
                2,
                events.size()
        );

        assertTrue(
                events.stream()
                        .allMatch(event -> event.id() != null)
        );

        assertTrue(
                events.stream()
                        .anyMatch(
                                event ->
                                        event.name()
                                                .equals("Rock Concert")
                        )
        );

        assertTrue(
                events.stream()
                        .anyMatch(
                                event ->
                                        event.name()
                                                .equals("Jazz Festival")
                        )
        );
    }

    @Test
    void getAll_shouldReturnEmptyList_whenNoEventsExist() {

        List<EventResponse> events =
                eventService.getAll();

        assertNotNull(events);
        assertTrue(events.isEmpty());
    }

    // =====================================================================
    // UPDATE
    // =====================================================================

    @Test
    void update_shouldPersistChangesAndIncrementVersion() {

        EventResponse created =
                eventService.create(
                        new CreateEventRequest(
                                "Rock Concert",
                                "Live concert",
                                Instant.parse(
                                        "2026-12-20T19:00:00Z"
                                )
                        )
                );

        assertNotNull(created.id());

        assertEquals(
                0L,
                created.version()
        );

        UpdateEventRequest updateRequest =
                new UpdateEventRequest(
                        "Rock Concert Updated",
                        "Updated concert description",
                        Instant.parse(
                                "2026-12-21T19:00:00Z"
                        )
                );

        EventResponse updated =
                eventService.update(
                        created.id(),
                        updateRequest
                );

        assertEquals(
                created.id(),
                updated.id()
        );

        assertEquals(
                1L,
                updated.version()
        );

        assertEquals(
                "Rock Concert Updated",
                updated.name()
        );

        assertEquals(
                "Updated concert description",
                updated.description()
        );

        assertEquals(
                Instant.parse(
                        "2026-12-21T19:00:00Z"
                ),
                updated.scheduledAt()
        );

        EventEntity persisted =
                eventRepository.findById(created.id())
                        .orElseThrow();

        assertEquals(
                1L,
                persisted.version()
        );

        assertEquals(
                "Rock Concert Updated",
                persisted.getName()
        );
    }

    @Test
    void update_shouldThrowEventNotFoundException_whenMissing() {

        UUID id = UUID.randomUUID();

        UpdateEventRequest request =
                new UpdateEventRequest(
                        "Updated",
                        "Updated description",
                        Instant.parse(
                                "2026-12-20T19:00:00Z"
                        )
                );

        assertThrows(
                EventNotFoundException.class,
                () -> eventService.update(
                        id,
                        request
                )
        );
    }

    // =====================================================================
    // PUBLISH
    // =====================================================================

    @Test
    void publish_shouldChangeStatusAndIncrementVersion() {

        EventResponse created =
                eventService.create(
                        new CreateEventRequest(
                                "Rock Concert",
                                "Live concert",
                                Instant.parse(
                                        "2026-12-20T19:00:00Z"
                                )
                        )
                );

        assertEquals(
                EventStatus.DRAFT,
                created.status()
        );

        EventResponse published =
                eventService.publish(created.id());

        assertEquals(
                created.id(),
                published.id()
        );

        assertEquals(
                EventStatus.PUBLISHED,
                published.status()
        );

        assertEquals(
                1L,
                published.version()
        );

        EventEntity persisted =
                eventRepository.findById(created.id())
                        .orElseThrow();

        assertEquals(
                EventStatus.PUBLISHED,
                persisted.getStatus()
        );

        assertEquals(
                1L,
                persisted.version()
        );
    }

    // =====================================================================
    // CANCEL
    // =====================================================================

    @Test
    void cancel_shouldChangeStatusAndIncrementVersion() {

        EventResponse created =
                eventService.create(
                        new CreateEventRequest(
                                "Rock Concert",
                                "Live concert",
                                Instant.parse(
                                        "2026-12-20T19:00:00Z"
                                )
                        )
                );

        EventResponse cancelled =
                eventService.cancel(created.id());

        assertEquals(
                created.id(),
                cancelled.id()
        );

        assertEquals(
                EventStatus.CANCELLED,
                cancelled.status()
        );

        assertEquals(
                1L,
                cancelled.version()
        );

        EventEntity persisted =
                eventRepository.findById(created.id())
                        .orElseThrow();

        assertEquals(
                EventStatus.CANCELLED,
                persisted.getStatus()
        );

        assertEquals(
                1L,
                persisted.version()
        );
    }

    // =====================================================================
    // COMPLETE
    // =====================================================================

    @Test
    void complete_shouldChangeStatusAndIncrementVersion() {

        EventResponse created =
                eventService.create(
                        new CreateEventRequest(
                                "Rock Concert",
                                "Live concert",
                                Instant.parse(
                                        "2026-12-20T19:00:00Z"
                                )
                        )
                );

        EventResponse published =
                eventService.publish(
                        created.id()
                );

        assertEquals(
                EventStatus.PUBLISHED,
                published.status()
        );

        assertEquals(
                1L,
                published.version()
        );

        EventResponse completed =
                eventService.complete(
                        created.id()
                );

        assertEquals(
                created.id(),
                completed.id()
        );

        assertEquals(
                EventStatus.COMPLETED,
                completed.status()
        );

        assertEquals(
                2L,
                completed.version()
        );

        EventEntity persisted =
                eventRepository.findById(created.id())
                        .orElseThrow();

        assertEquals(
                EventStatus.COMPLETED,
                persisted.getStatus()
        );

        assertEquals(
                2L,
                persisted.version()
        );
    }

    // =====================================================================
    // DELETE
    // =====================================================================

    @Test
    void delete_shouldRemoveEvent() {

        EventResponse created =
                eventService.create(
                        new CreateEventRequest(
                                "Rock Concert",
                                "Live concert",
                                Instant.parse(
                                        "2026-12-20T19:00:00Z"
                                )
                        )
                );

        UUID id = created.id();

        assertNotNull(id);

        assertTrue(
                eventRepository.existsById(id)
        );

        eventService.delete(id);

        assertFalse(
                eventRepository.existsById(id)
        );
    }

    @Test
    void delete_shouldThrowEventNotFoundException_whenMissing() {

        UUID id = UUID.randomUUID();

        assertThrows(
                EventNotFoundException.class,
                () -> eventService.delete(id)
        );
    }

    // =====================================================================
    // OPTIMISTIC LOCKING
    // =====================================================================

    @Test
    void concurrentUpdates_shouldFailWithOptimisticLockingException() {

        EventResponse created =
                eventService.create(
                        new CreateEventRequest(
                                "Rock Concert",
                                "Live concert",
                                Instant.parse(
                                        "2026-12-20T19:00:00Z"
                                )
                        )
                );

        UUID id = created.id();

        assertNotNull(id);

        /*
         * Load two different entity instances from two
         * different persistence contexts.
         */
        EventEntity first =
                transactionTemplate.execute(
                        status ->
                                eventRepository
                                        .findById(id)
                                        .orElseThrow()
                );

        EventEntity second =
                transactionTemplate.execute(
                        status ->
                                eventRepository
                                        .findById(id)
                                        .orElseThrow()
                );

        assertNotNull(first);
        assertNotNull(second);

        assertNotSame(
                first,
                second
        );

        assertEquals(
                id,
                first.id()
        );

        assertEquals(
                id,
                second.id()
        );

        assertEquals(
                0L,
                first.version()
        );

        assertEquals(
                0L,
                second.version()
        );

        /*
         * First transaction wins.
         */
        transactionTemplate.executeWithoutResult(
                status -> {

                    EventEntity current =
                            eventRepository
                                    .findById(id)
                                    .orElseThrow();

                    assertEquals(
                            0L,
                            current.version()
                    );

                    current.setName(
                            "Updated by transaction 1"
                    );

                    eventRepository.saveAndFlush(
                            current
                    );

                    /*
                     * Hibernate increments @Version during flush.
                     */
                    assertEquals(
                            1L,
                            current.version()
                    );
                }
        );

        /*
         * The second entity is stale.
         */
        assertEquals(
                id,
                second.id()
        );

        assertEquals(
                0L,
                second.version()
        );

        second.setName(
                "Updated by transaction 2"
        );

        assertThrows(
                OptimisticLockingFailureException.class,
                () ->
                        transactionTemplate.executeWithoutResult(
                                status -> {

                                    eventRepository.saveAndFlush(
                                            second
                                    );
                                }
                        )
        );

        /*
         * Verify that transaction 1 won.
         */
        EventEntity persisted =
                eventRepository.findById(id)
                        .orElseThrow();

        assertEquals(
                id,
                persisted.id()
        );

        assertEquals(
                "Updated by transaction 1",
                persisted.getName()
        );

        assertEquals(
                1L,
                persisted.version()
        );
    }
}