spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${EVENT_DB_URL}
    username: ${EVENT_DB_USERNAME}
    password: ${EVENT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: ${EVENT_SERVICE_PORT:8081}