name: booking-event-flow

services:

  event-service-db:
    image: postgres:${POSTGRES_VERSION:-17}
    container_name: booking-event-flow-event-db

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${EVENT_DB_NAME}
      POSTGRES_USER: ${EVENT_DB_USERNAME}
      POSTGRES_PASSWORD: ${EVENT_DB_PASSWORD}

    ports:
      - "${EVENT_DB_PORT:-5432}:5432"

    volumes:
      - event-service-db-data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${EVENT_DB_USERNAME} -d ${EVENT_DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    networks:
      - booking-event-flow-network

volumes:

  event-service-db-data:

networks:

  booking-event-flow-network:
    driver: bridge